const CSMEApp = [{
    FullName: {
        FirstName: "venkatesan",
        LastName: "kumar",
        MiddleName: "unknown",
        Alias: "",
    },
    Address: {
        AddressLine1: "25/b",
        AddressLine2: "anna nagar",
        Street: "balaji street",
        City: "vellore",
        Parish: "" ,
    },
    Gender: "MALE",
    DateOfBirth: "05/04/2000",
    Qualification: {
        HigherQualification: "B.SC",
        NameOfInstitution: "Anna University",
        DateCompleted: "05/04/2000",
        InstitutionAddress: {
            AddressLine1: "25/b",
            AddressLine2: "anna nagar",
            Street: "balaji street",
            City: "vellore",
            Parish: "" ,
        },
    },
    Country: "india",
    PlaceOfBirth: "vellore",
    Nationality: "indian",
    IdentificationID: "KJFS7418",
    MaterialStatus: "SINGLE",
    EntryDate: "12/21/2022",
    QualifyingID: "KJFS7418",
    PermitPeriodTo: "02/21/2023",
    PassportNumber: 1368,
    PassportExpiryDate: "12/21/2026",
    QualifyPRTDetails: {
    FullName: {
        FirstName: "venkatesan",
        LastName: "kumar",
        MiddleName: "unknown",
        Alias: "",
    },
    Address: {
        AddressLine1: "25/b",
        AddressLine2: "anna nagar",
        Street: "balaji street",
        City: "vellore",
        Parish: "" ,
    },
    Gender: "MALE",
    DateOfBirth: "05/04/2000",
    Country: "india",
    PlaceOfBirth: "vellore",
    Nationality: "indian",
    Qualification: "B.Sc",
    },
    Business: {
        EmploymentPosting: "Engineer",
        NatureOfBusiness: "Employed",
        Address: {
            AddressLine1: "25/b",
            AddressLine2: "anna nagar",
            Street: "balaji street",
            City: "vellore",
            Parish: "" ,
        },  
    },
    Purpose: {
        PurposeToJMC: "Employment",
    },
}]